### ISSUE TITLE
Build fails because is missing headroom.js package

### ISSUE THREAD

**Issue by laantorchaweb** [shipshapecode/ember-headroom#3]
It looks like unpkg is dropping support for bower and headroom library is possibly doing the same thing.

One temporary solution would be to reference this file directly on the bower.json:
`"headroom.js": "https://github.com/WickyNilliams/headroom.js/files/950268/bower.zip"`

headroom.js issue:
https://github.com/WickyNilliams/headroom.js/issues/268

**Comment by RobbieTheWagner** [comment]
We should probably use ember-cli-node-assets here. I can take a stab at making the switch.

**Comment by RobbieTheWagner** [comment]
@laantorchaweb I just published `1.0.0` can you please give it a try?

**Comment by laantorchaweb** [comment]
@rwwagner90 it's working now, thank you!

**Comment by RobbieTheWagner** [comment]
You're welcome!
